export const RECEIVE_HEADLINES = "RECEIVE_HEADLINES";
export const RECEIVE_RESOURCES = "RECEIVE_RESOURCES";
export const RECEIVE_TAGS = "RECEIVE_TAGS";
export const SEARCH_HEADLINES = "SEARCH_HEADLINES";
export const SELECT_TAGS = "SELECT_TAGS";
