export const REQUEST_HEADLINES = "REQUEST_HEADLINES";
export const RECEIVE_HEADLINES = "RECEIVE_HEADLINES";
export const REQUEST_RESOURCES = "REQUEST_RESOURCES";
export const RECEIVE_RESOURCES = "RECEIVE_RESOURCES";
